dist: xenial
language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"

install:
  - pip install tox-travis

script:
  - tox

after_success:
  - tox -e coverage,codecov

deploy:
  - provider: pypi
    user: ruohoruotsi
    password:
      secure: "qfZA8+AZ7OL6DGc6kMqpBzw1lG1Kh1QXN5JoV8XDHkh9mZp7mLI7iLnjFS/Mi94EMMhpKNHX2Q9+0x4qywmAMS0dLSTu9hGaff/eEXbo9DIPxNs1mcH897ngaEwaoEMq4RD02x+qSKZIpQBuy7msXvLw6ct6za1VOPYQyhDOkEyy1Y0pEjnrCY7pu0mX0jViOw7iXCRvvnNy9kmuNRj6KdBiv4iCCUCJfLuAeHKiB1aD0Nw4BbOEJa2YwDpmgyOBtQ0dKkE50ljDX981zKxfyuQ5PTSmyUwK2L/k6NFfCkeu05bFdo2ZuwR0ry7+tqvgD/3MVbyTqdPfvQnhLSoYQ1NN60uJCwVfXa8mXBnZJ87QaYNNAPXzbGsdP+V385M51LCTev/Bz3qLzYiC762FiOYuoaOeuCyW7ZaLfCP4u0GrPtT+hCm2hZXFhY3vEYRM4csVcn8qybAMEzJfHF98WFTCm+ECIKWROedtEN4U8DA6Si836zeBpveM6/Epb4wHVo9h65GRbhxz3qC8XZ35gnulZjQ0y821jAyr9v8v/Yl08edZJUzUnvjccopuoOEf0sVN6TwQtjZX1sSJcaO8rb6YV5/9CXM3XIDN+jwHtKYv0F9HYOVMNoON6Y6y/A9XH74nvAQ4wdYfVfDocyA+MBzI1dSdlTefKU30LX7durs="
      distributions: sdist bdist_wheel
    on:
      python: 3.6
      repo: ruohoruotsi/iranlowo
      tags: true